/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DetectionStep: typeof import('./components/steps/DetectionStep.vue')['default']
    DynamicCaptcha: typeof import('./components/DynamicCaptcha.vue')['default']
    ForgotPassword: typeof import('./components/ForgotPassword.vue')['default']
    ImageSelectionStep: typeof import('./components/steps/ImageSelectionStep.vue')['default']
    ReviewStep: typeof import('./components/steps/ReviewStep.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./components/Snackbar.vue')['default']
    UploadProgress: typeof import('./components/UploadProgress.vue')['default']
  }
}
